spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/recipes
    username: postgres
    password: DbMaj7#5b9/Bb-POSTGRES
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  batch:
    jdbc:
      initialize-schema: always
server:
  port: 8081